# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-03 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='author',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='question',
        ),
        migrations.AlterField(
            model_name='question',
            name='added_at',
            field=models.DateField(blank=True),
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
